name: Deploy Content

on:
  push:
    paths:
      - 'content/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci

    - name: Build (if needed)
      run: npm run build

    - name: Deploy to AWS Lightsail
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key:      ${{ secrets.SSH_KEY }}
        script: |
          cd ~/ConceptComsWebsite
          git pull origin main
          npm ci
          npm run build
          ./deploy_beta.sh
